name: Build and Release macOS App

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools py2app pillow

      - name: Install jaraco.text for py2app compatibility
        run: |
          pip install jaraco.text

      - name: Verify nockchain-wallet executable exists
        run: |
          ls -la nockchain-wallet
          file nockchain-wallet
      - name: Import Code Signing Certificate    
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.p12
          security create-keychain -p "$MACOS_CERTIFICATE_PWD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_CERTIFICATE_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          echo "Available code signing identities:"
          security find-identity -v -p codesigning
      - name: Build macOS app
        run: |
          # Build the app
          python setup.py py2app

          # Verify signing
          codesign -dv dist/NockGUIWallet.app || echo "Code signing verification failed"

      - name: Verify app bundle
        run: |
          ls -la dist/
          ls -la dist/NockGUIWallet.app/Contents/Resources/
          test -f dist/NockGUIWallet.app/Contents/Resources/nockchain-wallet && echo "nockchain-wallet bundled successfully"

      - name: Create app archive
        run: |
          cd dist
          zip -r NockGUIWallet.app.zip NockGUIWallet.app

      - name: Upload app to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NockGUIWallet-macOS
          path: dist/NockGUIWallet.app.zip

      - name: Upload app to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/NockGUIWallet.app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
